# Request
trajectory_msgs/JointTrajectory joint_traj # joint trajectory for visualization
geometry_msgs/Pose[] cartesian_traj # corresponding cartesian trajectory
float64[3] aff_screw_axis # screw axis unit vector
float64[3] aff_location # location of the screw axis
string ref_frame # reference frame for EE FK computation
geometry_msgs/Pose aff_ref_pose # Reference pose for approach motion, corresponding to the affordance zero
---
# Result
bool success # whether planning and visualization was successful
