# Request
trajectory_msgs/JointTrajectory joint_traj # joint trajectory for visualization
geometry_msgs/Pose[] cartesian_traj # corresponding cartesian trajectory
geometry_msgs/Vector3[] aff_screw_axes # vector of screw axes
geometry_msgs/Point[] aff_locations # locations of the corresponding screw axes
geometry_msgs/Pose[] aff_ref_poses # Reference poses for approach motion, corresponding to the affordance zero
string ref_frame # reference frame for EE FK computation
---
# Result
bool success # whether planning and visualization was successful
int64 validation_time_usecs # amount of microseconds taken to validate self-collision and joint limits
