# Request
trajectory_msgs/JointTrajectory joint_traj # joint trajectory for planning and visualization
string ref_frame # reference frame name
string tool_frame # tool frame name. The position trajectory of this frame is visualized
---
# Result
bool success # whether planning and visualization was successful
