# *** ROS-related attributes pertaining to kinova_gen3_7dof_robotiq_2f_85 *** #

global_parameter_server:
  ros__parameters:
    # --- Robot Name ---
    cca_robot: "kinova_gen3_7dof_robotiq_2f_85" # This package must be named cc_affordance_<cca_robot>_description

    # --- Action Server ---
    cca_robot_as: "/joint_trajectory_controller/follow_joint_trajectory" # Follow joint trajectory action server to execute trajectory on the robot

    # --- Topics ---
    cca_joint_states_topic: "/joint_states" # Joint states topic name

    # --- Robot Description ---
    cca_robot_description_parameter: "robot_description" # Robot description parameter name

    # --- Planning Group ---
    cca_planning_group: "manipulator" # MoveIt planning group name

    # --- Rviz Fixed Frame ---
    rviz_fixed_frame: "base_link" # Fixed frame for viewing in Rviz
