# Request
trajectory_msgs/JointTrajectory joint_traj # joint trajectory for planning and visualization
float64[3] aff_screw_axis # screw axis unit vector
float64[3] aff_location # location of the screw axis
string ref_frame # reference frame for EE FK computation
---
# Result
bool success # whether planning and visualization was successful
