# Request
trajectory_msgs/JointTrajectory joint_traj # joint trajectory for planning and visualization
float64[3] aff_screw_axis # screw axis unit vector
float64[3] aff_location # location of the screw axis
string robot_description # robot_description parameter name
string planning_group # planning group name
string rviz_fixed_frame # fixed frame name in rviz to plot EE markers wrt to
string ref_frame # reference frame for EE FK computation
string tool_frame # tool frame name. The position trajectory of this frame is visualized
---
# Result
bool success # whether planning and visualization was successful
