cca_ros_viz_msgs/PlannerConfig planner_config
cca_ros_viz_msgs/TaskDescription task_description
cca_ros_viz_msgs/KinematicState start_state
bool visualize_trajectory true
bool execute_trajectory false
---
bool success
---

